// Static list of the seven partner insurance companies (see PROJECT_BRIEF.md).
// Not generated by faker — these are real partners.

export interface InsuranceCompanyFixture {
  id: string;
  name: string;
  shortName: string;
}

export const insuranceCompanies: InsuranceCompanyFixture[] = [
  { id: 'renessans', name: 'Ренессанс Страхование', shortName: 'Ренессанс' },
  { id: 'ugoria', name: 'Югория', shortName: 'Югория' },
  { id: 'soglasie', name: 'Согласие', shortName: 'Согласие' },
  { id: 'zetta', name: 'Зетта Страхование', shortName: 'Зетта' },
  { id: 'rosgosstrah', name: 'Росгосстрах', shortName: 'РГС' },
  { id: 'sogaz', name: 'СОГАЗ', shortName: 'СОГАЗ' },
  { id: 'euroins', name: 'Евроинс', shortName: 'Евроинс' },
  { id: 'energogarant', name: 'Энергогарант', shortName: 'Энергогарант' },
];
