/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Авторизация агента */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход из системы (инвалидация токена) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновление access token через refresh token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль текущего агента */
        get: operations["getCurrentAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить профиль (контакты, настройки) */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все данные для главной страницы (одним запросом) */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список полисов агента */
        get: operations["getPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Детали полиса */
        get: operations["getPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Расторжение полиса */
        post: operations["cancelPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{id}/prolong": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Пролонгация полиса (создание расчёта на основе старого) */
        post: operations["prolongPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculations/osago": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Расчёт ОСАГО (параллельный запрос ко всем 7 СК) */
        post: operations["calculateOsago"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить расчёт по ID */
        get: operations["getCalculation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculations/{id}/proceed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Оформить полис на основе выбранного предложения */
        post: operations["proceedWithCalculation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insurance-companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список доступных страховых компаний */
        get: operations["getInsuranceCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список марок автомобилей */
        get: operations["getVehicleBrands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Модели по марке */
        get: operations["getVehicleModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            /** @description true при успехе, false при ошибке */
            success: boolean;
            /** @description Данные ответа (тип зависит от endpoint) */
            data?: unknown;
            error?: {
                /**
                 * @description Машиночитаемый код ошибки
                 * @example VALIDATION_ERROR
                 */
                code?: string;
                /**
                 * @description Человекочитаемое сообщение (на русском)
                 * @example Заполните все обязательные поля
                 */
                message?: string;
                /** @description Дополнительные детали (например, список полей с ошибками) */
                details?: Record<string, never> | null;
            } | null;
            meta?: {
                /** @example 1 */
                page?: number;
                /** @example 20 */
                pageSize?: number;
                /** @example 142 */
                total?: number;
            } | null;
        };
        Pagination: {
            /** @default 1 */
            page: number;
            /** @default 20 */
            pageSize: number;
        };
        Agent: {
            /** Format: uuid */
            id: string;
            /**
             * @description Индивидуальный код продавца (например, "00531")
             * @example 00531
             */
            ikp?: string;
            /** @example Иванова Елена Викторовна */
            fullName: string;
            /**
             * Format: email
             * @example ivanova@example.ru
             */
            email: string;
            /** @example +79991234567 */
            phone?: string;
            /**
             * Format: date
             * @example 1976-04-15
             */
            birthDate?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "unknown";
            /** @example Красноярский край */
            region?: string;
            /** @example Минусинск */
            district?: string;
            /**
             * @description ФЛ, ИП, СЗ, ЮЛ
             * @enum {string}
             */
            legalType?: "individual" | "ip" | "sz" | "ul";
            /** @example Категория 3 */
            category?: string;
            /** @example Марченко Елена Георгиевна */
            curatorName?: string;
            /** Format: date */
            joinDate?: string;
            /** Format: date */
            firstSaleDate?: string | null;
            /** @enum {string} */
            status: "active" | "inactive" | "blocked";
            /**
             * Format: float
             * @description Общая сумма комиссии за всё время
             */
            totalCommission?: number;
        };
        Policy: {
            /** Format: uuid */
            id: string;
            /** @example РРР-12345678 */
            number: string;
            /** @enum {string} */
            type: "OSAGO" | "NS" | "TICK" | "MORTGAGE";
            /** @enum {string} */
            status: "active" | "expired" | "cancelled" | "pending" | "processing";
            /** @example Петров Иван Сергеевич */
            clientName?: string;
            /** @example +79991234567 */
            clientPhone?: string;
            vehicleInfo?: components["schemas"]["VehicleInfo"];
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /**
             * Format: float
             * @description Стоимость полиса
             */
            premium?: number;
            /**
             * Format: float
             * @description Комиссия агента
             */
            commission?: number;
            insuranceCompany?: components["schemas"]["InsuranceCompany"];
            /** Format: uuid */
            agentId?: string;
            /** Format: date-time */
            createdAt?: string;
            cancellationReason?: string | null;
        };
        VehicleInfo: {
            /** @example XTA21099120123456 */
            vin?: string;
            /** @example А123ВС99 */
            licensePlate?: string;
            /** @example 2018 */
            year?: number;
            /** @example ВАЗ */
            brand?: string;
            /** @example 2110 */
            model?: string;
            /** @example 76.5 */
            power?: number;
            /** @enum {string} */
            category?: "B" | "C" | "D";
        };
        OwnerInfo: {
            /** @example Петров Иван Сергеевич */
            fullName: string;
            /**
             * Format: date
             * @example 1985-06-15
             */
            birthDate: string;
            /**
             * Format: date
             * @example 2010-08-20
             */
            licenseDate?: string;
            /** @example 4509 */
            passportSeries?: string;
            /** @example 123456 */
            passportNumber?: string;
            /**
             * Format: float
             * @description Коэффициент бонус-малус
             * @example 0.85
             */
            kbm?: number;
        };
        InsuranceCompany: {
            id: string;
            /** @example РЕСО-Гарантия */
            name: string;
            /** @example РЕСО */
            shortName?: string;
            /** Format: uri */
            logo?: string | null;
        };
        CalculationOffer: {
            insuranceCompany: components["schemas"]["InsuranceCompany"];
            /** @description Стоимость полиса */
            premium: number;
            /** @description Комиссия агента */
            commission: number;
            /**
             * Format: date-time
             * @description До какого времени действительно предложение
             */
            validUntil?: string;
            /** @description Особые условия */
            conditions?: string[];
            /** @description Рекомендательный балл (для сортировки) */
            recommendationScore?: number;
            /** @description Можно ли оформить полис на этих условиях */
            canProceed?: boolean;
        };
        UrgentAction: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "prolongation" | "client_request" | "payment" | "document" | "other";
            /** @example Пролонгация Петров И.С. истекает завтра */
            title: string;
            description?: string;
            /** Format: date-time */
            dueDate: string;
            /** @enum {string} */
            priority?: "low" | "medium" | "high" | "critical";
            relatedEntityId?: string | null;
            /** @enum {string|null} */
            relatedEntityType?: "policy" | "client" | "request" | null;
        };
        DashboardMetrics: {
            /** @description Заработано в этом месяце (₽) */
            monthlyEarnings?: number;
            /** @description Изменение % к прошлому месяцу */
            monthlyEarningsChange?: number;
            /** @description Количество активных полисов */
            activePolicies?: number;
            activePoliciesChange?: number;
            /** @description Пролонгаций в этом месяце */
            monthlyRenewals?: number;
            /** @description Срочных пролонгаций (требуют действия) */
            urgentRenewals?: number;
            /** @description Конверсия расчётов в полисы (%) */
            conversionRate?: number;
            conversionRateChange?: number;
        };
        LoginRequest: {
            /**
             * @description ИКП агента или email
             * @example 00531
             */
            login: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            /** @description JWT access token */
            token?: string;
            refreshToken?: string;
            /** @description Срок жизни access token в секундах */
            expiresIn?: number;
            agent?: components["schemas"]["Agent"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Успешная авторизация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["LoginResponse"];
                    };
                };
            };
            /** @description Неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description Новый access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            token?: string;
                            expiresIn?: number;
                        };
                    };
                };
            };
        };
    };
    getCurrentAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Agent"];
                    };
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email?: string;
                    phone?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Agent"];
                    };
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            metrics?: components["schemas"]["DashboardMetrics"];
                            recentPolicies?: components["schemas"]["Policy"][];
                            urgentActions?: components["schemas"]["UrgentAction"][];
                        };
                    };
                };
            };
        };
    };
    getPolicies: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: "active" | "expired" | "cancelled" | "pending";
                type?: "OSAGO" | "NS" | "TICK" | "MORTGAGE";
                insuranceCompanyId?: string;
                /** @description Поиск по ФИО клиента, номеру полиса, номеру машины */
                search?: string;
                dateFrom?: string;
                dateTo?: string;
                sortBy?: "createdAt" | "premium" | "commission" | "endDate";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Policy"][];
                    };
                };
            };
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Policy"];
                    };
                };
            };
        };
    };
    cancelPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                    comment?: string;
                };
            };
        };
        responses: {
            /** @description Расторжение инициировано */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    prolongPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Создан расчёт для пролонгации */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            calculationId?: string;
                        };
                    };
                };
            };
        };
    };
    calculateOsago: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    vehicle: components["schemas"]["VehicleInfo"];
                    owner: components["schemas"]["OwnerInfo"];
                    additionalDrivers?: components["schemas"]["OwnerInfo"][];
                    /**
                     * @description Срок страхования в днях
                     * @default 365
                     */
                    period?: number;
                };
            };
        };
        responses: {
            /** @description Расчёт выполнен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            calculationId?: string;
                            offers?: components["schemas"]["CalculationOffer"][];
                            failedCompanies?: {
                                companyId?: string;
                                reason?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    getCalculation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    proceedWithCalculation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    insuranceCompanyId: string;
                };
            };
        };
        responses: {
            /** @description Полис создан (в статусе processing) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Policy"];
                    };
                };
            };
        };
    };
    getInsuranceCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["InsuranceCompany"][];
                    };
                };
            };
        };
    };
    getVehicleBrands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            id?: string;
                            name?: string;
                        }[];
                    };
                };
            };
        };
    };
    getVehicleModels: {
        parameters: {
            query: {
                brandId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
}
